AWSTemplateFormatVersion: "2010-09-09"
Description: EC2 Instance Create

# ------------------------------------------------------------#
# Input Parameters
# ------------------------------------------------------------#
Parameters:
  Stage:
    Type: String
    Default: "dev"

  EC2InstanceAMI:
    Type: String
    Default: "ami-0c3fd0f5d33134a76"


Resources:

  # ------------------------------------------------------------#
  #  SecurityGroup for Web
  # ------------------------------------------------------------#
  WebSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "-"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: "0.0.0.0/0"
      Tags:
        - Key: Name
          Value: aws-challenge
        - Key: aws-challenge
          Value: vol.1

  # ------------------------------------------------------------#
  #  IAM Role for EC2
  # ------------------------------------------------------------#
  EC2IAMRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub "${Stage}-aws-challenge-1-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonEC2FullAccess"
        - "arn:aws:iam::aws:policy/AmazonEC2RoleforSSM"

  EC2InstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: "/"
      Roles:
        - Ref: EC2IAMRole
      InstanceProfileName: !Sub "${Stage}-aws-challenge-1-profile"

  # ------------------------------------------------------------#
  #  EC2
  # ------------------------------------------------------------#
  EC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !Ref EC2InstanceAMI
      InstanceType: t2.micro
      IamInstanceProfile: !Ref EC2InstanceProfile
      DisableApiTermination: false
      EbsOptimized: false
      SecurityGroupIds:
        - !Ref WebSecurityGroup
      UserData: !Base64 |
        #!/bin/bash
        yum update -y
        yum install -y httpd git
        git clone https://github.com/tomonoriminegishi/aws-challenge-3.git
        cat aws-challenge-3/etc/99-happyholidays >> /etc/update-motd.d/30-banner
        chmod 755 /etc/update-motd.d/30-banner
        update-motd
        usermod -a -G apache ec2-user
        chown -R ec2-user:apache /var/www
        chmod 2775 /var/www
        find /var/www -type d -exec chmod 2775 {} \;
        find /var/www -type f -exec chmod 0664 {} \;
        cd /var/www/html
        touch maintenance.html
        echo '<html lang="ja"><head><title>AWS Challenge!</title><link rel="stylesheet" href="https://s3.amazonaws.com/exampleloadbalancer-net/demo_site_asset/css/styles.css"></head><body style="background-color: #232f3e;"><div class="container"><div class="jumbotron text-center"><h2 class="display-1 text-center" style="color:#232f3e;">503 Service Unavailable</h2><h2 class="display-4 text-center" style="color:#232f3e;margin-bottom:50px">error!error!errror!</h2><iframe src="https://giphy.com/embed/q6RoNkLlFNjaw" width="480" height="480" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/cat-q6RoNkLlFNjaw">via GIPHY</a></p></div></div></body></html>' > maintenance.html
        chown -R ec2-user:apache /var/www/html/maintenance.html
        cat << EOF > .htaccess
        ErrorDocument 503 /maintenance.html

        <IfModule mod_rewrite.c>
          RewriteEngine On
          RewriteCond %{REQUEST_URI} !=/maintenance.html
          RewriteRule ^.*$ - [R=503,L]
        </IfModule>
        EOF
        sed -i -e 's/AllowOverride none/AllowOverride All/' /etc/httpd/conf/httpd.conf
        sed -i -e 's/AllowOverride None/AllowOverride All/' /etc/httpd/conf/httpd.conf
        systemctl start httpd
        systemctl enable httpd
      Tags:
        - Key: Name
          Value: aws-challenge
        - Key: aws-challenge
          Value: You can not access in ec2.

# ------------------------------------------------------------#
# Output Parameters
# ------------------------------------------------------------#
Outputs:
  Endpoint:
    Description: "here we go! It is the beginning of a fun time."
    Value: !Join
      - ""
      - - "http://"
        - !GetAtt EC2Instance.PublicDnsName
